from setuptools import setup, find_packages

setup(
    name="sf20k",
    version="0.1",
    description="SF20K dataset",
    author="Ridouane Ghermi",
    author_email="ridouane.ghermi@inria.fr",
    packages=find_packages(),
    install_requires=[
        "torch",
        "torchvision",
        "transformers",
        "accelerate",
        "peft",
        "numpy",
        "pandas",
        "Pillow",
        "decord",
        "opencv-python",
        "tqdm",
        "datasets",
        "pyyaml",
        "pycocoevalcap",
        "openai",
        "google-genai",
        "packaging",
        "einops",
        "timm",
    ],
)